// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview A flow for generating a summarized AI diagnosis report from a medical image.
 *
 * - generateDiagnosisSummary - A function that handles the diagnosis summary generation process.
 * - GenerateDiagnosisSummaryInput - The input type for the generateDiagnosisSummary function.
 * - GenerateDiagnosisSummaryOutput - The return type for the generateDiagnosisSummary function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateDiagnosisSummaryInputSchema = z.object({
  medicalImageDataUri: z
    .string()
    .describe(
      "A medical image, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
  patientDetails: z.string().describe('Relevant patient details for context.'),
  imagingModality: z.string().describe('The imaging modality used (e.g., X-ray, MRI, CT scan).'),
});
export type GenerateDiagnosisSummaryInput = z.infer<
  typeof GenerateDiagnosisSummaryInputSchema
>;

const GenerateDiagnosisSummaryOutputSchema = z.object({
  diagnosisSummary: z.string().describe('A summarized AI diagnosis report.'),
  potentialConditions: z
    .string()
    .describe('Potential medical conditions identified in the image.'),
  relevantFindings: z.string().describe('Relevant findings observed in the image.'),
});
export type GenerateDiagnosisSummaryOutput = z.infer<
  typeof GenerateDiagnosisSummaryOutputSchema
>;

export async function generateDiagnosisSummary(
  input: GenerateDiagnosisSummaryInput
): Promise<GenerateDiagnosisSummaryOutput> {
  return generateDiagnosisSummaryFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateDiagnosisSummaryPrompt',
  input: {schema: GenerateDiagnosisSummaryInputSchema},
  output: {schema: GenerateDiagnosisSummaryOutputSchema},
  prompt: `You are an AI assistant that specializes in analyzing medical images and providing summarized diagnosis reports for doctors.

  Given a medical image, patient details, and the imaging modality, generate a concise diagnosis summary, list potential conditions, and highlight relevant findings.

  Patient Details: {{{patientDetails}}}
  Imaging Modality: {{{imagingModality}}}
  Medical Image: {{media url=medicalImageDataUri}}

  Ensure the diagnosis summary is clear, informative, and helpful for the doctor's diagnostic process.
  Format the output into three sections:
  - Diagnosis Summary
  - Potential Conditions
  - Relevant Findings`,
});

const generateDiagnosisSummaryFlow = ai.defineFlow(
  {
    name: 'generateDiagnosisSummaryFlow',
    inputSchema: GenerateDiagnosisSummaryInputSchema,
    outputSchema: GenerateDiagnosisSummaryOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
